spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl

# MinIO
minio.url=http://localhost:9000
minio.access.key=mykey
minio.secret.key=mysecret
minio.bucket=image-storage
